### ISSUE TITLE
这个是只能用于Heroku,还是其它的Node服务器也可以?

### ISSUE THREAD

**Issue by WeihuaGu** [VincentChanX/shadowsocks-over-websocket#25]
因为heroku访问的实在是太慢了,我试了另一个node的服务器,弄上去就显示这个
```
[2018-09-02 22:20:45.695] [ERROR] local - [2]: an error of server connection occured Error: unexpected server response (400)
    at ClientRequest._req.on (/home/happ/projects/now/shadowsocks-over-websocket/node_modules/_ws@2.3.1@ws/lib/WebSocket.js:650:26)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
[2018-09-02 22:20:45.695] [INFO] local - [2]: close event[code = 'reserved for extensions'] of server connection has been triggered
[2018-09-02 22:20:45.697] [INFO] local - [2]: end event of client connection has been triggered
[2018-09-02 22:20:45.697] [INFO] local - [2]: close event[had error = false] of client connection has been triggered


```

**Comment by VincentChanX** [comment]
理论上支持的 你用的是什么云服务

顾玮华 <notifications@github.com> 于2018年9月2日周日 下午4:57写道：

**Comment by WeihuaGu** [comment]
@VincentChanX 免费版的now,这个支持node.js,实在不行,它还支持docker.

**Comment by liuzhijie443** [comment]
@WeihuaGu 在哪有？搭建成功了吗?

**Comment by WeihuaGu** [comment]
@liuzhijie443 没有,我都试了,都不行,我怀疑是端口转发的问题.但是我今天发现了一个新的空间商,https://www.evennode.com/ 它不光提供nodejs,还提供python,免费版可以使用一个月,我用这个试一试,看能不能搭建成功.

**Comment by liuzhijie443** [comment]
@WeihuaGu 一个月的没有太大意义

**Comment by WeihuaGu** [comment]
@liuzhijie443 我意思是先用这个试一试看看shadowsocks-over-websocket可以用在除了heroku的其它服务器上不,我昨天试了下,客户端报了服务器返回502,看服务器的log,没显示什么.这个不用邮件确认,有邮箱就能注册使用一个月,速度还行,便于测试.

这年月想同时免费,并且私有,并且大陆可以访问的nodejs空间确实很少,我没找到,但是如果这个项目可以用于其它nodejs服务其,那比如有人买的有nodejs的服务器,或者能找到很便宜的就可以用.因为heroku确实访问太慢了

**Comment by liuzhijie443** [comment]
@WeihuaGu heroku绑定域名CF的CDN加速可以达到100M网速没问题，速度非常快

**Comment by liuzhijie443** [comment]
@WeihuaGu 我搭建成功了，速度很慢，留个联系方式跟你交流一下

**Comment by WeihuaGu** [comment]
@liuzhijie443 点下我的主页,有我的邮箱.我也是按照教程,先把代码传上去,在它的网页添加了相应的环境变量,为什么不行,是不是需要改动下哪里. 感谢:)

**Comment by liuzhijie443** [comment]
@WeihuaGu 把server.js中监听的IP和端口换成0.0.0.0和80重新上传，重启，打开主页出现Upgrade Required就是成功了，密码和加密方式应该是在local.js

**Comment by liuzhijie443** [comment]
@WeihuaGu https://github.com/nodejs/node-v0.x-archive/wiki/Node-Hosting

**Comment by WeihuaGu** [comment]
@liuzhijie443 再次感谢,已经可以使用了:)
