### ISSUE TITLE
客户端说未接到服务端相应（503）

### ISSUE THREAD

**Issue by angsheng** [VincentChanX/shadowsocks-over-websocket#35]
把package.json 中依赖改为了"bufferutil": "^4.0.1"，能够部署，
访问后，服务端无异常，但是客户端报错
an error of server connection occured Error: unexpected server response (503)
    at ClientRequest._req.on (F:xxx\node_modules\ws\lib\WebSocket.js:650:26)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)

不知何解，求大神解答。

**Comment by angsheng** [comment]
知道怎么回事了。忘了配置服务端变量了。
